---
- name: Install nginx
  yum: 
    name: nginx
    state: present

- name: Copy nginx configuration for wordpress
  template: 
    src: default.conf 
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld: 
    port: "{{ nginx_port }}/tcp" 
    permanent: yes 
    state: enabled 
    immediate: yes

- name: mginx service state
  service: 
    name: nginx
    state: started 
    enabled: yes