---
- name: test Netbox vm add
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files: netbox.yml
  
  vars:
    netbox_state: present


  tasks:

  - name: Create OS platform
    netbox.netbox.netbox_platform:
      netbox_url: "{{netbox_url}}"
      netbox_token: "{{netbox_token}}"
      data:
        name: "{{ hostvars[item]['summary.config.guestFullName'] }}"
      state: "{{ netbox_state }}"
      validate_certs: no
    loop: "{{ groups['all'] }}"

  - name: Update vcpus, memory and disk of an existing virtual machine
    netbox.netbox.netbox_virtual_machine:
      netbox_url: "{{netbox_url}}"
      netbox_token: "{{netbox_token}}"
      data:
        name: "{{ hostvars[item]['guest.hostName'] }}"
        cluster: Test
#        primary_ip4: "{{ hostvars[item]['ansible_host'] }}"
        vcpus: "{{ hostvars[item]['config.hardware.numCPU'] }}"
        memory: "{{ hostvars[item]['config.hardware.memoryMB'] }}"
        disk: "{{ hostvars[item]['summary.config.numVirtualDisks'] }}"
        platform: "{{ hostvars[item]['summary.config.guestFullName'] }}"
        comments: "Test Ansible"
      state: "{{ netbox_state }}"
      validate_certs: no
    loop: "{{groups['all']}}"


  - name: debug output
    debug:
      var: hostvars['cvcln']['config.hardware.device'][12]['capacityInKB'] / 1048576 | int

  - name: debug output
    debug:
      var: hostvars['cvcln']['config.hardware.device']|lenght


#    loop:
#     - apvm1 
#    loop: "{{groups['rhel8_64Guest']}}"
  
  # - name: Update vcpus, memory and disk of an existing virtual machine
  #   netbox.netbox.netbox_virtual_machine:
  #     netbox_url: "{{netbox_url}}"
  #     netbox_token: "{{netbox_token}}"
  #     data:
  #       name: 'Test001'
  #       cluster: Test
  #       vcpus: '4'
  #       memory: '8'
  #       disk: '4'
  #       comments: "Testowa Maszyna"
  #     state: absent
  #     validate_certs: no