---
- name: test Netbox vm add
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files: netbox.yml


  tasks:
  - name: Update vcpus, memory and disk of an existing virtual machine
    netbox.netbox.netbox_virtual_machine:
      netbox_url: "{{netbox_url}}"
      netbox_token: "{{netbox_token}}"
      data:
        name: "{{ hostvars[item]['guest.hostName'] }}"
        cluster: Test
#        primary_ip4: "{{ hostvars[item]['ansible_host'] }}"
        vcpus: "{{ hostvars[item]['config.hardware.numCPU'] }}"
        memory: "{{ hostvars[item]['config.hardware.memoryMB'] }}"
        disk: "{{ hostvars[item]['summary.config.numVirtualDisks'] }}"
      state: present
      validate_certs: no
    loop: "{{groups['rhel8_64Guest']}}"
#    loop:
#     - apvm1 
#    loop: "{{groups['rhel8_64Guest']}}"
  
  # - name: Update vcpus, memory and disk of an existing virtual machine
  #   netbox.netbox.netbox_virtual_machine:
  #     netbox_url: "{{netbox_url}}"
  #     netbox_token: "{{netbox_token}}"
  #     data:
  #       name: 'Test001'
  #       cluster: Test
  #       vcpus: '4'
  #       memory: '8'
  #       disk: '4'
  #       comments: "Testowa Maszyna"
  #     state: absent
  #     validate_certs: no