---
- name: test Netbox vm add
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files: netbox.yml
  
  vars:
    netbox_state: absent
    vmware_inv_grp: all


  tasks:

  - name: Remove existing machines
    netbox.netbox.netbox_virtual_machine:
      netbox_url: "{{netbox_url}}"
      netbox_token: "{{netbox_token}}"
      data:
        name: "{{ hostvars[item]['guest.hostName'] }}"
        cluster: Test
        vcpus: "{{ hostvars[item]['config.hardware.numCPU'] }}"
        memory: "{{ hostvars[item]['config.hardware.memoryMB'] }}"
        disk: "{{ hostvars[item]['summary.config.numVirtualDisks'] }}"
        platform: "{{ hostvars[item]['summary.config.guestFullName'] }}"
        comments: "Test Ansible"
      state: "{{ netbox_state }}"
      validate_certs: no
    loop: "{{groups[vmware_inv_grp]}}"

  - name: Remove OS platform
    netbox.netbox.netbox_platform:
      netbox_url: "{{netbox_url}}"
      netbox_token: "{{netbox_token}}"
      data:
        name: "{{ hostvars[item]['summary.config.guestFullName'] }}"
      state: "{{ netbox_state }}"
      validate_certs: no
    loop: "{{ groups[vmware_inv_grp] }}"