---
- name: Gather and display active services
  hosts: all
  gather_facts: yes
  
#  vars: 
#    service_name: "{{fact_service_name}}.service"

  tasks:
  - name: Print service facts
    ansible.builtin.service_facts:

  - name: Print to log
    ansible.builtin.debug:
      var: ansible_facts['services'][item + '.service']
    loop: "{{ service_name }}"