---
- name: Gather and display packages info
  hosts: all
  gather_facts: yes

  tasks:
  - name: Print packages facts
    ansible.builtin.package_facts:

  - name: Print to log
    ansible.builtin.debug:
      var: ansible_facts['packages'][item]
    loop: "{{ package_name }}"