---
- name: Provision VM from template
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Login to oVirt
    redhat.rhv.ovirt_auth:
      url: "{{ engine_url | default(lookup('env','OVIRT_URL')) | default(omit) }}"
      hostname: "{{ engine_fqdn | default(lookup('env','OVIRT_HOSTNAME')) | default(omit) }}"
      username: "{{ engine_user | default(lookup('env','OVIRT_USERNAME')) | default(omit) }}"
      password: "{{ engine_password | default(lookup('env','OVIRT_PASSWORD')) | default(omit) }}"
      ca_file: "{{ engine_cafile | default(lookup('env','OVIRT_CAFILE')) | default(omit) }}"
      insecure: "{{ engine_insecure | default(true) }}"
    when: ovirt_auth is undefined or not ovirt_auth
    register: loggedin

  - name: Create and run RHEL8 VM from template
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name | default('change_me')}}"
      template: 11_jsk_rhel8template
      cluster: "{{ cluster | default('Default')}}"
      memory: "{{vm_memory | default('2GiB')}}"
      high_availability: true
      description: "{{ description | default(omit) }}"
      state: stopped
      wait: yes


  - name: Create initial snap
    redhat.rhv.ovirt_snapshot:
      auth: "{{ ovirt_auth }}"
      vm_name: "{{ vm_name | default('change_me')}}"
      wait: yes
      state: present
      description: Initial_snap

  - name: Add JustCreated tag to the VM
    redhat.rhv.ovirt_tag:
      auth: "{{ ovirt_auth }}"
      name: just_created
      state: attached
      vms:
        - "{{ vm_name | default('change_me')}}"
      
  - name: Start vm
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name | default('change_me')}}"
      state: running
      wait: yes

  - name: Pause after VM creates
    pause:
      seconds: 30

  - name: Revoke the SSO token
    redhat.rhv.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"