---
- name: Provision VM from template
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Login to oVirt
    redhat.rhv.ovirt_auth:
      url: "{{ engine_url | default(lookup('env','OVIRT_URL')) | default(omit) }}"
      hostname: "{{ engine_fqdn | default(lookup('env','OVIRT_HOSTNAME')) | default(omit) }}"
      username: "{{ engine_user | default(lookup('env','OVIRT_USERNAME')) | default(omit) }}"
      password: "{{ engine_password | default(lookup('env','OVIRT_PASSWORD')) | default(omit) }}"
      ca_file: "{{ engine_cafile | default(lookup('env','OVIRT_CAFILE')) | default(omit) }}"
      insecure: "{{ engine_insecure | default(true) }}"
    when: ovirt_auth is undefined or not ovirt_auth
    register: loggedin


  - name: Add Production tag to the VM
    redhat.rhv.ovirt_tag:
      auth: "{{ ovirt_auth }}"
      name: production
      state: attached
      vms:
        - "{{ vm_name | default('change_me')}}"
      
  - name: ARemove JustCreated tag from VM assignment
    redhat.rhv.ovirt_tag:
      auth: "{{ ovirt_auth }}"
      name: just_created
      state: absent
      vms:
        - "{{ vm_name | default('change_me')}}"  
        
  - name: Revoke the SSO token
    redhat.rhv.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"