---
- name: Provision VM from template
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
#    username:
#    url:
#    password:
    datacenter: Default
    cluster: Default
    vm_memory: 1GiB
    vm_name: test02
    description: testvm

  tasks:
  - name: Login to oVirt
    ovirt_auth:
      url: "{{ engine_url | default(lookup('env','OVIRT_URL')) | default(omit) }}"
      hostname: "{{ engine_fqdn | default(lookup('env','OVIRT_HOSTNAME')) | default(omit) }}"
      username: "{{ engine_user | default(lookup('env','OVIRT_USERNAME')) | default(omit) }}"
      password: "{{ engine_password | default(lookup('env','OVIRT_PASSWORD')) | default(omit) }}"
      ca_file: "{{ engine_cafile | default(lookup('env','OVIRT_CAFILE')) | default(omit) }}"
      insecure: "{{ engine_insecure | default(true) }}"
    when: ovirt_auth is undefined or not ovirt_auth
    register: loggedin

  - name: Create and run RHEL8 VM from template
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: 11_jsk-rhel8template
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      high_availability: true
      description: "{{ description }}"
      state: stopped
      wait: yes


  - name: Create initial snap
    redhat.rhv.ovirt_snapshot:
      auth: "{{ ovirt_auth }}"
      vm_name: "{{ vm_name }}"
      wait: yes
      state: present
      description: Initial_snap

  - name: Add JustCreated tag to the VM
    redhat.rhv.ovirt_tag:
      name: just_created
      state: attached
      vms:
        - "{{ vm_name }}"
      
  - name: Start vm
    redhat.rhv.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      state: running
      wait: yes

  - name: Pause after VM creates
    pause:
      seconds: 40

#  - name: Revoke the SSO token
#    ovirt_auth:
#      state: absent
#      ovirt_auth: "{{ ovirt_auth }}"