---
roles:
  - name: common-role
    src: https://github.com/jskorzyn/common-role.git

  - name: mariadb-role
    src: https://github.com/jskorzyn/mariadb-role.git

  - name: nginx-role
    src: https://github.com/jskorzyn/nginx-role.git

  - name: phpfpm-role
    src: https://github.com/jskorzyn/phpfpm-role.git

  - name: wordpress-role
    src: https://github.com/jskorzyn/wordpress-role.git