---
- name: Set machine hostname
  ansible.builtin.hostname:
    name: "{{inventory_hostname | default('change_me')}}.redhat.lab"
    use: systemd

- name: Clear registration settings
  community.general.redhat_subscription:
    state: absent

- name: Register to Sattellite with activation key
  community.general.redhat_subscription:
    state: present
    force_register: true
    activationkey: RHEL8
    org_id: RedHatDemoLab

- name: Install Epel
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: yes